#                                                              -*- Makefile -*-
# Simics module makefile
#

SIMICS_API := 6
THREAD_SAFE:=yes
MODULE_CLASSES = my_device

DML_FILES = my_device.dml

include $(MODULE_MAKEFILE)
